Algoritmo "Procedimentos - Aula 2A - Módulo 2"
// Autor(a)    : Thayna Vitoria Basselli
// Data atual  : 26/05/2022
Var
// Seção de Declarações das variáveis 
   resultado: inteiro
   
   procedimento somar (i, j: inteiro)
   inicio
         resultado <- i + j
   fimprocedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   somar(10, 20)
   Escreval (Resultado)

Fimalgoritmo